# Generated by Django 2.1.1 on 2019-03-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='google_maps_url',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='location',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
